export default [{
  id: 1,
  title: "Чебуреки",
  weight: "300",
  price: "200",
  description: "В состав входят: говядина, свинина, мука в/с, яйцо, лук, перец, специи, чеснок, вода питьевая",
  image: "/static/shop/img/chebureki.jpg",
}, {
  id: 2,
  title: "Пельмени с говядиной",
  weight: "1000",
  price: "200",
  description: "Категория A, без ГМО. В составе: охлажденная говядина, свинина, мука в/с, яйцо, лук, соль, перец, вода питьевая",
  image: "/static/shop/img/pelmeni-s-govyadinoy.jpg",
}, {
  id: 3,
  title: "Манты",
  weight: "530",
  price: "200",
  description: "В состав входят: говядина, свинина, мука в/с, яйцо, лук, перец, специи, вода питьевая",
  image: "/static/shop/img/manti.jpg",
}, {
  id: 4,
  title: "Вареники с картофелем",
  weight: "1000",
  price: "200",
  description: "В состав входят: картофель, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-kartofelem.jpg",
}, {
  id: 5,
  title: "Вареники с картофелем и грибами",
  weight: "1000",
  price: "200",
  description: "В состав входят: картофель, грибы, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-kartofelem-i-gribami.jpg",
}, {
  id: 6,
  title: "Вареники с творогом",
  weight: "1000",
  price: "200",
  description: "В состав входят: творог, сахар, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-tvorogom.jpg",
}, {
  id: 7,
  title: "Котлеты",
  weight: "430",
  price: "200",
  description: "В состав входят: говядина, свинина, яйцо, хлеб, жир, лук, соль, перец, специи",
  image: "/static/shop/img/koteleti.jpg",
}]