export default [{
  id: 1,
  title: "Чебуреки",
  weight: "300 гр.",
  price: 85,
  description: "В состав входят: говядина, свинина, мука в/с, яйцо, лук, перец, специи, чеснок, вода питьевая",
  image: "/static/shop/img/chebureki.jpg",
}, {
  id: 2,
  title: "Пельмени с говядиной",
  weight: ["400 гр.", "500 гр.", "950 гр.", "1000 гр."],
  price: [145, 195, 365, 360],
  description: "Категория A, без ГМО. В составе: охлажденная говядина, свинина, мука в/с, яйцо, лук, соль, перец, вода питьевая",
  image: "/static/shop/img/pelmeni-s-govyadinoy.jpg",
}, {
  id: 3,
  title: "Пельмени с говядиной 'Для вас'",
  weight: ["400 гр.", "1000 гр."],
  price: [130, 315],
  description: "Категория B, без ГМО. В составе: охлажденная говядина, свинина, мука в/с, яйцо, лук, соль, перец, вода питьевая",
  image: "/static/shop/img/pelmeni-category-b.jpg",
}, {
  id: 4,
  title: "Пельмени 'Для вас'",
  weight: ["400 гр.", "1000 гр."],
  price: [120, 290],
  description: "Категория B, без ГМО. В составе: охлажденная говядина, свинина, мука в/с, яйцо, лук, соль, перец, вода питьевая",
  image: "/static/shop/img/pelmeni-s-govyadinoy.jpg",
}, {
  id: 5,
  title: "Манты",
  weight: "530 гр.",
  price: 150,
  description: "В состав входят: говядина, свинина, мука в/с, яйцо, лук, перец, специи, вода питьевая",
  image: "/static/shop/img/manti.jpg",
}, {
  id: 6,
  title: "Вареники с картофелем",
  weight: ["400 гр.", "1000 гр."],
  price: [60, 140],
  description: "В состав входят: картофель, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-kartofelem.jpg",
}, {
  id: 7,
  title: "Вареники с картофелем и грибами",
  weight: ["400 гр.", "1000 гр."],
  price: [65, 145],
  description: "В состав входят: картофель, грибы, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-kartofelem-i-gribami.jpg",
}, {
  id: 8,
  title: "Вареники с творогом",
  weight: ["400 гр.", "1000 гр."],
  price: 200,
  description: "В состав входят: творог, сахар, мука в/с, яйцо, соль, вода питьевая",
  image: "/static/shop/img/vareniki-s-tvorogom.jpg",
}, {
  id: 9,
  title: "Котлеты",
  weight: "430 гр.",
  price: 150,
  description: "Категория А. В состав входят: говядина, свинина, яйцо, хлеб, жир, лук, соль, перец, специи",
  image: "/static/shop/img/koteleti.jpg",
}, {
  id: 10,
  title: "Котлеты с чесноком",
  weight: "430 гр.",
  price: 150,
  description: "Категория А. В состав входят: охлажденная говядина, свинина, яйцо, хлеб, жир, лук, соль, перец, специи, чеснок",
  image: "/static/shop/img/koteleti-s-chesnokom.jpg",
}]